Delete Icon
because

```
C:\Users\joelr\Documents\kolmorotzzet (kolmorotshitt)\Artistic Setups\rosshoyt\MIDI-File-Player>git reset --hard
error: invalid path 'MIDIFile-PlaybackiTesting Project/Icon?'
fatal: Could not reset index file to revision 'HEAD'.
```

ueah that file is brogen.